// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmsyveegoosjwnpwemrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtc3l2ZWVnb29zanducHdlbXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDg3MjMsImV4cCI6MjA2MDgyNDcyM30.Cp6GgifYC-pV7VL4RUn3r_5dbQvWhBXVqa6II0f8mGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);